/////////////
// Schemas //
/////////////

///////////////////////////
// Specific data Schemas //
///////////////////////////

export const clientSchema = ["id", "name", "createdAt", "updatedAt"]
export const currencySchema = [
  "id",
  "name",
  "symbol",
  "symbolNative",
  "decimalDigits",
  "code",
  "rounding",
  "namePlural",
  "createdAt",
  "updatedAt",
]
export const commoditiesSchema = [
  "id",
  "clientId",
  "enabled",
  "bidType",
  "name",
  "baseSymbolId",
  "dtnCommodityId",
  "useConvertedUom",
  "useCustomUom",
  "customUomRate",
  "primaryUomId",
  "convertedUomId",
  "calculationTypeId",
  "inSessionRoundingId",
  "onCloseRoundingId",
  "baseCurrencyId",
  "useConvertedCurrency",
  "convertToCurrencyId",
  "currencyConversionRateId",
  "createdBy",
  "updatedBy",
  "createdAt",
  "updatedAt",
  "client",
  "calculationType",
  "baseCurrency",
  "convertToCurrency",
  "currencyConversionRate",
  "baseSymbol",
  "dtnCommodity",
  "primaryUom",
  "convertedUom",
  "inSessionRounding",
  "onCloseRounding",
  "createdByUser",
  "updatedByUser",
]

export const commoditySchema = [
  "id",
  "clientId",
  "enabled",
  "bidType",
  "name",
  "baseSymbolId",
  "dtnCommodityId",
  "useConvertedUom",
  "useCustomUom",
  "customUomRate",
  "primaryUomId",
  "convertedUomId",
  "calculationTypeId",
  "inSessionRoundingId",
  "onCloseRoundingId",
  "baseCurrencyId",
  "useConvertedCurrency",
  "convertToCurrencyId",
  "currencyConversionRateId",
  "createdBy",
  "updatedBy",
  "createdAt",
  "updatedAt",
]

export const dtnCommoditiesSchema = [
  "id",
  "name",
  "baseSymbolId",
  "currencyId",
  "uomId",
  "poundsPerBushel",
  "active",
  "createdAt",
  "updatedAt",
  "measureUnit",
  "currency",
  "baseSymbol",
]

export const dtnCommoditiesUOMSchema = [
  "id",
  "conversionRate",
  "dtnCommodityId",
  "fromUomId",
  "toUomId",
  "createdAt",
  "updatedAt",
]

export const dtnFuturesSymbolSchema = [
  "id",
  "baseSymbol",
  "name",
  "marketId",
  "exchangeCurrencyId",
  "active",
  "createdAt",
  "updatedAt",
  "exchangeCurrency",
]

export const locationsSchema = [
  "id",
  "clientId",
  "enabled",
  "name",
  "displayName",
  "address1",
  "address2",
  "city",
  "state",
  "postalCode",
  "county",
  "country",
  "inventoryLocation",
  "marketRegion",
  "destinationLocation",
  "contractLocation",
  "other",
  "pricingGroup",
  "privateGroupId",
  "createdBy",
  "updatedBy",
  "createdAt",
  "updatedAt",
]

export const locationSchema = [
  "id",
  "clientId",
  "enabled",
  "name",
  "displayName",
  "address1",
  "address2",
  "city",
  "state",
  "postalCode",
  "county",
  "country",
  "inventoryLocation",
  "marketRegion",
  "destinationLocation",
  "contractLocation",
  "other",
  "pricingGroup",
  "privateGroupId",
  "createdBy",
  "updatedBy",
  "createdAt",
  "updatedAt",
  "commodities",
]
